ALTER TABLE [COMPRAS-ARTICULOS]
add constraint FK_COMPRAS_ARTICULOS_codigo foreign key(codigo) --"FK_COMPRA_ARTICULOS_codigo" es un NOMBRE QUE SE LE DA A LA RESTRICCION PARA IDENTIFICARLA
references ARTICULOS(codigo)
ON UPDATE CASCADE